name: trigger_action
on:
  workflow_dispatch

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ github.repository_owner }}
          repo: pyopenms-docs
          github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          github_user: ${{ github.repository_owner }}
          workflow_file_name: test-pr-sphinx.yml
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
